// -*- C++ -*-
#ifndef ThePEG_PDFCuts_H
#define ThePEG_PDFCuts_H
//
// This is the declaration of the <!id>PDFCuts<!!id> class.
//
// CLASSDOC SUBSECTION Description:
//
// The <!id>PDFCuts<!!id> class is used to specify cuts on scale and
// momentum fractions for which a <!class>PDFBase<!!class> object is
// expected to give parton densities. It is used to estimate upper
// limita on the parton densities to be generated by a
// <!class>PDFBase<!!class> object.
//
// CLASSDOC SUBSECTION See also:
//
// <a href="http:PDFBase.html">PDFBase.h</a>.
// 

#include "ThePEG/Config/ThePEG.h"
#include "ThePEG/Utilities/Interval.h"
// #include "PDFCuts.fh"
// #include "PDFCuts.xh"

namespace ThePEG {

class PDFCuts {

public:

  inline PDFCuts();
  inline PDFCuts(const PDFCuts &);
  inline ~PDFCuts();
  // Standard ctors and dtor

  inline PDFCuts(const Interval<double> & newL,
		 const SInterval & newScale, const Energy2 & newSMax);
  // Construction from members.

  PDFCuts(const KinematicalCuts &, bool first, const SInterval & S,
	  const SInterval & sHat);
  PDFCuts(const KinematicalCuts &, bool first, Energy maxEnergy);
  // Construction from a KinematicalCuts object, using the values for
  // the first incoming parton (or not).

  inline PDFCuts & operator=(const PDFCuts &);
  //  assignment operator.

public:

  inline double lMin() const;
  inline double lMax() const;
  inline double xMin() const;
  inline double xMax() const;
  // The minimum and maximum values of log(1/x) and x.

  inline Energy2 scaleMin() const;
  inline Energy2 scaleMax() const;
  // The limits on the scale to be used.

  inline Energy2 scaleMax(double x) const;
  inline Energy2 scaleMaxL(double l) const;
  // The maximum scale for a given momentum fraction.

  inline Energy2 sMax() const;
  // The maximum invariant mass squared of the colliding particles.

private:

  Interval<double> theL;
  // The minimum and maximum values of log(1/x).

  SInterval theScale;
  // The limits on the scale to be used.

  Energy2 theSMax;
  // The maximum invariant mass squared of the colliding particles.

};

}

#include "PDFCuts.icc"
#ifndef ThePEG_TEMPLATES_IN_CC_FILE
// #include "PDFCuts.tcc"
#endif

#endif /* ThePEG_PDFCuts_H */
