SOURCES = GenEventConverter.cc

OBJECTS = GenEventConverter.o

DOCFILES = JamesRandom.h Lorentz5Vector.h LorentzRotation.h LorentzVector.h \
           PhysicalConstants.h RandomEngine.h Rotation.h SystemOfUnits.h \
           ThreeVector.h Transverse.h CLHEP.h GenEventConverter.h \
           RandExponential.h RandBreitWigner.h Matrix.h

INCLUDEFILES = $(DOCFILES) JamesRandom.fh Lorentz5Vector.fh \
               Lorentz5Vector.icc LorentzRotation.fh LorentzVector.fh \
               RandomEngine.fh Rotation.fh ThreeVector.fh Transverse.icc \
               Transverse.fh GenEventConverter.icc RandExponential.fh \
               RandBreitWigner.fh Matrix.fh

DISTFILES = $(INCLUDEFILES) $(SOURCES) Makefile

INCLUDEDIR = CLHEPWrap

include ../Config/Makefile.common

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.

  GenEventConverter.o: \
  GenEventConverter.cc \
  GenEventConverter.h \
  ../../ThePEG/Config/ThePEG.h \
  ../../ThePEG/Config/config.h \
  ../../ThePEG/Pointer/Ptr.h \
  ../../ThePEG/Pointer/RCPtr.fh \
  ../../ThePEG/Pointer/PtrTraits.h \
  ../../ThePEG/Pointer/RCPtr.h \
  ../../ThePEG/Pointer/ReferenceCounted.h \
  ../../ThePEG/Pointer/ReferenceCounted.icc \
  ../../ThePEG/Pointer/RCPtr.icc \
  ../../ThePEG/Utilities/Rebinder.fh \
  ../../ThePEG/Utilities/Interval.fh \
  ../../ThePEG/Utilities/ClassDescription.fh \
  ../../ThePEG/Interface/InterfaceBase.fh \
  ../../ThePEG/Persistency/PersistentOStream.fh \
  ../../ThePEG/Persistency/PersistentIStream.fh \
  ../../ThePEG/Config/Units.h \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.fh \
  ../../ThePEG/CLHEPWrap/LorentzVector.fh \
  ../../ThePEG/CLHEPWrap/CLHEP.h \
  ../../ThePEG/CLHEPWrap/ThreeVector.fh \
  ../../ThePEG/CLHEPWrap/Transverse.fh \
  ../../ThePEG/CLHEPWrap/SystemOfUnits.h \
  ../../ThePEG/Utilities/UnitIO.h \
  ../../ThePEG/Config/Constants.h \
  ../../ThePEG/Config/std.h \
  ../../ThePEG/Config/Pointers.h \
  ../../ThePEG/Config/Containers.h \
  ../../ThePEG/Utilities/FixedSizeAllocator.h \
  ../../ThePEG/Utilities/Debug.h \
  ../../ThePEG/Utilities/Debug.icc \
  ../../ThePEG/Utilities/FixedSizeAllocator.icc \
  ../../ThePEG/EventRecord/Event.h \
  ../../ThePEG/EventRecord/Particle.h \
  ../../ThePEG/EventRecord/EventConfig.h \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.h \
  ../../ThePEG/CLHEPWrap/LorentzVector.h \
  ../../ThePEG/CLHEPWrap/Transverse.h \
  ../../ThePEG/CLHEPWrap/Transverse.icc \
  ../../ThePEG/Utilities/Direction.h \
  ../../ThePEG/Utilities/Direction.xh \
  ../../ThePEG/Utilities/Exception.h \
  ../../ThePEG/Utilities/Exception.fh \
  ../../ThePEG/Utilities/sstream.h \
  ../../ThePEG/Utilities/Exception.icc \
  ../../ThePEG/Utilities/Direction.icc \
  ../../ThePEG/Utilities/Math.h \
  ../../ThePEG/Utilities/Math.icc \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.icc \
  ../../ThePEG/CLHEPWrap/LorentzRotation.h \
  ../../ThePEG/CLHEPWrap/LorentzRotation.fh \
  ../../ThePEG/Utilities/ClassDescription.h \
  ../../ThePEG/Utilities/Named.h \
  ../../ThePEG/Utilities/Named.icc \
  ../../ThePEG/Utilities/ClassTraits.h \
  ../../ThePEG/Utilities/DescriptionList.h \
  ../../ThePEG/Utilities/DescriptionList.icc \
  ../../ThePEG/Utilities/ClassDescription.icc \
  ../../ThePEG/Utilities/ClassDescription.tcc \
  ../../ThePEG/EventRecord/ColourBase.h \
  ../../ThePEG/EventRecord/EventInfoBase.h \
  ../../ThePEG/EventRecord/EventInfoBase.icc \
  ../../ThePEG/EventRecord/ColourLine.h \
  ../../ThePEG/EventRecord/ColourSinglet.h \
  ../../ThePEG/EventRecord/ColourSinglet.icc \
  ../../ThePEG/EventRecord/ColourLine.icc \
  ../../ThePEG/EventRecord/ColourBase.icc \
  ../../ThePEG/EventRecord/SpinBase.h \
  ../../ThePEG/EventRecord/SpinBase.icc \
  ../../ThePEG/EventRecord/Particle.icc \
  ../../ThePEG/PDT/ParticleData.h \
  ../../ThePEG/PDT/PDT.h \
  ../../ThePEG/PDT/PDT.icc \
  ../../ThePEG/CLHEPWrap/PhysicalConstants.h \
  ../../ThePEG/Interface/Interfaced.h \
  ../../ThePEG/Interface/InterfacedBase.h \
  ../../ThePEG/Utilities/HoldFlag.h \
  ../../ThePEG/Utilities/HoldFlag.icc \
  ../../ThePEG/Interface/InterfacedBase.xh \
  ../../ThePEG/Interface/InterfaceBase.h \
  ../../ThePEG/Interface/InterfaceBase.xh \
  ../../ThePEG/Interface/InterfaceBase.icc \
  ../../ThePEG/Interface/InterfacedBase.icc \
  ../../ThePEG/Interface/Interfaced.icc \
  ../../ThePEG/Utilities/Selector.h \
  ../../ThePEG/Utilities/Selector.icc \
  ../../ThePEG/Utilities/Selector.tcc \
  ../../ThePEG/PDT/WidthGenerator.fh \
  ../../ThePEG/PDT/MassGenerator.fh \
  ../../ThePEG/PDT/DecayMode.fh \
  ../../ThePEG/PDT/ParticleData.icc \
  ../../ThePEG/EventRecord/Particle.tcc \
  ../../ThePEG/EventRecord/StandardSelectors.h \
  ../../ThePEG/EventRecord/SelectorBase.h \
  ../../ThePEG/EventRecord/SelectorBase.icc \
  ../../ThePEG/EventRecord/ParticleTraits.h \
  ../../ThePEG/EventRecord/Event.icc \
  ../../ThePEG/EventRecord/Collision.h \
  ../../ThePEG/EventRecord/Collision.icc \
  ../../ThePEG/EventRecord/Step.h \
  ../../ThePEG/EventRecord/Step.icc \
  ../../ThePEG/EventRecord/SubProcess.h \
  ../../ThePEG/EventRecord/SubProcess.icc \
  ../../ThePEG/EventRecord/SubProcess.tcc \
  ../../ThePEG/EventRecord/Step.tcc \
  ../../ThePEG/EventRecord/Collision.tcc \
  ../../ThePEG/EventRecord/Event.tcc \
  GenEventConverter.icc \
  ../../ThePEG/Handlers/EventHandler.h \
  ../../ThePEG/Handlers/CollisionHandler.h \
  ../../ThePEG/Handlers/PartialCollisionHandler.h \
  ../../ThePEG/Handlers/HandlerBase.h \
  ../../ThePEG/Handlers/HandlerBase.icc \
  ../../ThePEG/Handlers/HandlerGroup.h \
  ../../ThePEG/Handlers/HandlerGroup.icc \
  ../../ThePEG/Handlers/HandlerGroup.tcc \
  ../../ThePEG/Handlers/Hint.h \
  ../../ThePEG/Handlers/Hint.icc \
  ../../ThePEG/Handlers/StepHandler.h \
  ../../ThePEG/Handlers/StepHandler.icc \
  ../../ThePEG/Handlers/LastXCombInfo.h \
  ../../ThePEG/PDF/PDF.fh \
  ../../ThePEG/Handlers/LastXCombInfo.icc \
  ../../ThePEG/Handlers/PartialCollisionHandler.xh \
  ../../ThePEG/Handlers/PartialCollisionHandler.icc \
  ../../ThePEG/Handlers/CollisionHandler.xh \
  ../../ThePEG/Utilities/Interval.h \
  ../../ThePEG/Utilities/Interval.icc \
  ../../ThePEG/Utilities/Interval.tcc \
  ../../ThePEG/Handlers/CollisionHandler.icc \
  ../../ThePEG/Handlers/EventHandler.xh \
  ../../ThePEG/Repository/Strategy.fh \
  ../../ThePEG/Handlers/SamplerBase.fh \
  ../../ThePEG/Handlers/EventHandler.icc \
  ../../ThePEG/Handlers/XComb.h \
  ../../ThePEG/Handlers/SubProcessHandler.fh \
  ../../ThePEG/PDF/PartonExtractor.fh \
  ../../ThePEG/PDF/PartonBin.h \
  ../../ThePEG/PDF/PDFBase.h \
  ../../ThePEG/PDF/PDFCuts.h \
  ../../ThePEG/PDF/PDFCuts.icc \
  ../../ThePEG/PDF/PDFBase.xh \
  ../../ThePEG/PDF/PDFBase.icc \
  ../../ThePEG/PDF/PartonBin.icc \
  ../../ThePEG/PDF/PartonBinInstance.h \
  ../../ThePEG/PDF/PartonBinInstance.icc \
  ../../ThePEG/Utilities/VSelector.h \
  ../../ThePEG/Utilities/VSelector.icc \
  ../../ThePEG/Utilities/VSelector.tcc \
  ../../ThePEG/MatrixElement/MEBase.h \
  ../../ThePEG/MatrixElement/DiagramBase.h \
  ../../ThePEG/MatrixElement/ColourLines.h \
  ../../ThePEG/MatrixElement/ColourLines.icc \
  ../../ThePEG/MatrixElement/DiagramBase.fh \
  ../../ThePEG/MatrixElement/DiagramBase.xh \
  ../../ThePEG/MatrixElement/DiagramBase.icc \
  ../../ThePEG/MatrixElement/Amplitude.h \
  ../../ThePEG/Config/Complex.h \
  ../../ThePEG/MatrixElement/Amplitude.icc \
  ../../ThePEG/MatrixElement/MEBase.icc \
  ../../ThePEG/Handlers/XComb.icc \
  ../../ThePEG/StandardModel/StandardModelBase.h \
  ../../ThePEG/StandardModel/AlphaEMBase.h \
  ../../ThePEG/StandardModel/StandardModelBase.fh \
  ../../ThePEG/StandardModel/AlphaEMBase.icc \
  ../../ThePEG/StandardModel/CKMBase.h \
  ../../ThePEG/StandardModel/CKMBase.icc \
  ../../ThePEG/StandardModel/AlphaSBase.h \
  ../../ThePEG/StandardModel/AlphaSBase.icc \
  ../../ThePEG/StandardModel/StandardModelBase.icc \
  ../../ThePEG/Repository/EventGenerator.h \
  ../../ThePEG/Repository/EventGenerator.fh \
  ../../ThePEG/Repository/RandomGenerator.h \
  ../../ThePEG/CLHEPWrap/RandomEngine.fh \
  ../../ThePEG/Repository/RandomGenerator.icc \
  ../../ThePEG/Repository/UseRandom.h \
  ../../ThePEG/Repository/UseRandom.icc \
  ../../ThePEG/Repository/CurrentGenerator.fh \
  ../../ThePEG/Repository/EventGenerator.xh \
  ../../ThePEG/Repository/EventGenerator.icc \
  ../../ThePEG/Repository/EventGenerator.tcc

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
