SOURCES = LesHouchesReader.cc

LIBOBJECTS = LesHouchesReader.o

OBJECTS = libThePEGLesHouches.so

LIBFILES = $(OBJECTS)

DOCFILES = LesHouchesReader.h

INCLUDEFILES = $(DOCFILES) LesHouchesReader.fh LesHouchesReader.icc

DISTFILES = $(INCLUDEFILES) $(SOURCES) Makefile

INCLUDEDIR = LesHouches

include ../Config/Makefile.common

libThePEGLesHouches.so: $(LIBOBJECTS)

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.

  LesHouchesReader.o: \
  LesHouchesReader.cc \
  LesHouchesReader.h \
  ../../ThePEG/Handlers/HandlerBase.h \
  ../../ThePEG/Interface/Interfaced.h \
  ../../ThePEG/Config/ThePEG.h \
  ../../ThePEG/Config/config.h \
  ../../ThePEG/Pointer/Ptr.h \
  ../../ThePEG/Pointer/RCPtr.fh \
  ../../ThePEG/Pointer/PtrTraits.h \
  ../../ThePEG/Pointer/RCPtr.h \
  ../../ThePEG/Pointer/ReferenceCounted.h \
  ../../ThePEG/Pointer/ReferenceCounted.icc \
  ../../ThePEG/Pointer/RCPtr.icc \
  ../../ThePEG/Utilities/Rebinder.fh \
  ../../ThePEG/Utilities/Interval.fh \
  ../../ThePEG/Utilities/ClassDescription.fh \
  ../../ThePEG/Interface/InterfaceBase.fh \
  ../../ThePEG/Persistency/PersistentOStream.fh \
  ../../ThePEG/Persistency/PersistentIStream.fh \
  ../../ThePEG/Config/Units.h \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.fh \
  ../../ThePEG/CLHEPWrap/LorentzVector.fh \
  ../../ThePEG/CLHEPWrap/CLHEP.h \
  ../../ThePEG/CLHEPWrap/ThreeVector.fh \
  ../../ThePEG/CLHEPWrap/Transverse.fh \
  ../../ThePEG/CLHEPWrap/SystemOfUnits.h \
  ../../ThePEG/Utilities/UnitIO.h \
  ../../ThePEG/Config/Constants.h \
  ../../ThePEG/Config/std.h \
  ../../ThePEG/Config/Pointers.h \
  ../../ThePEG/Config/Containers.h \
  ../../ThePEG/Utilities/FixedSizeAllocator.h \
  ../../ThePEG/Utilities/Debug.h \
  ../../ThePEG/Utilities/Debug.icc \
  ../../ThePEG/Utilities/FixedSizeAllocator.icc \
  ../../ThePEG/Interface/InterfacedBase.h \
  ../../ThePEG/Utilities/Named.h \
  ../../ThePEG/Utilities/Named.icc \
  ../../ThePEG/Utilities/ClassDescription.h \
  ../../ThePEG/Utilities/ClassTraits.h \
  ../../ThePEG/Utilities/DescriptionList.h \
  ../../ThePEG/Utilities/DescriptionList.icc \
  ../../ThePEG/Utilities/ClassDescription.icc \
  ../../ThePEG/Utilities/ClassDescription.tcc \
  ../../ThePEG/Utilities/HoldFlag.h \
  ../../ThePEG/Utilities/HoldFlag.icc \
  ../../ThePEG/Interface/InterfacedBase.xh \
  ../../ThePEG/Interface/InterfaceBase.h \
  ../../ThePEG/Interface/InterfaceBase.xh \
  ../../ThePEG/Utilities/Exception.h \
  ../../ThePEG/Utilities/Exception.fh \
  ../../ThePEG/Utilities/sstream.h \
  ../../ThePEG/Utilities/Exception.icc \
  ../../ThePEG/Interface/InterfaceBase.icc \
  ../../ThePEG/Interface/InterfacedBase.icc \
  ../../ThePEG/Interface/Interfaced.icc \
  ../../ThePEG/Handlers/HandlerBase.icc \
  LesHouchesReader.fh \
  LesHouchesReader.icc \
  ../../ThePEG/Interface/ClassDocumentation.h \
  ../../ThePEG/Interface/ClassDocumentation.fh \
  ../../ThePEG/Interface/ClassDocumentation.icc \
  ../../ThePEG/Persistency/PersistentOStream.h \
  ../../ThePEG/Config/Complex.h \
  ../../ThePEG/Persistency/PersistentOStream.xh \
  ../../ThePEG/Persistency/PersistentOStream.icc \
  ../../ThePEG/Persistency/PersistentIStream.h \
  ../../ThePEG/Persistency/InputDescription.h \
  ../../ThePEG/Persistency/InputDescription.icc \
  ../../ThePEG/Persistency/PersistentIStream.icc \
  ../../ThePEG/Persistency/PersistentIStream.tcc

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
