#!/bin/sh
export ThePEG_INSTALL_PATH=@path@
VERSION=""
if [ $# -gt 1 ]; then
  if [ "$1" = "-v" ]; then
    VERSION="-$2"
    shift 2
  fi
fi

HEADLESS=""
if [ "$1" = "--classcheck" ]; then
    HEADLESS="-Djava.awt.headless=true"
fi

export LD_LIBRARY_PATH=${ThePEG_INSTALL_PATH}:${LD_LIBRARY_PATH}
exec @java@ ${HEADLESS} -jar ${ThePEG_INSTALL_PATH}/ThePEG.jar ${ThePEG_INSTALL_PATH}/setupThePEG${VERSION}.bin $*
