Document: thepeg
Title: Debian thepeg Manual
Author: <insert document author here>
Abstract: This manual describes what thepeg is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/thepeg/thepeg.sgml.gz

Format: postscript
Files: /usr/share/doc/thepeg/thepeg.ps.gz

Format: text
Files: /usr/share/doc/thepeg/thepeg.text.gz

Format: HTML
Index: /usr/share/doc/thepeg/html/index.html
Files: /usr/share/doc/thepeg/html/*.html

  
