SOURCES = SpinInfo.cc HelicityVertex.cc FermionSpinInfo.cc

OBJECTS = SpinInfo.o HelicityVertex.o FermionSpinInfo.o

DOCFILES = SpinInfo.h HelicityVertex.h FermionSpinInfo.h

INCLUDEFILES = $(DOCFILES) SpinInfo.fh SpinInfo.icc HelicityVertex.fh\
               HelicityVertex.icc FermionSpinInfo.fh FermionSpinInfo.icc

DISTFILES = $(INCLUDEFILES) $(SOURCES) Makefile

INCLUDEDIR = Helicity

include ../Config/Makefile.common

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
