DOCFILES = Ptr.h PtrTraits.h RCPtr.h ReferenceCounted.h

INCLUDEFILES = $(DOCFILES) RCPtr.fh RCPtr.icc ReferenceCounted.icc 

DISTFILES = $(INCLUDEFILES) $(SOURCES) Makefile

INCLUDEDIR = Pointer

include ../Config/Makefile.common

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.


# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
