SOURCES = PersistentOStream.cc PersistentIStream.cc

OBJECTS = PersistentOStream.o PersistentIStream.o

DOCFILES = InputDescription.h PersistentIStream.h PersistentOStream.h

INCLUDEFILES = $(DOCFILES) InputDescription.icc PersistentIStream.fh \
            PersistentIStream.icc PersistentIStream.tcc PersistentIStream.xh \
            PersistentOStream.fh PersistentOStream.icc PersistentOStream.xh 

DISTFILES = $(INCLUDEFILES) $(SOURCES) Makefile

INCLUDEDIR = Persistency

include ../Config/Makefile.common

# DO NOT DELETE THIS LINE -- g++dep uses it.
# DO NOT PUT ANYTHING AFTER THIS LINE, IT WILL GO AWAY.

  PersistentOStream.o: \
  PersistentOStream.cc \
  PersistentOStream.h \
  ../../ThePEG/Config/ThePEG.h \
  ../../ThePEG/Config/config.h \
  ../../ThePEG/Pointer/Ptr.h \
  ../../ThePEG/Pointer/RCPtr.fh \
  ../../ThePEG/Pointer/PtrTraits.h \
  ../../ThePEG/Pointer/RCPtr.h \
  ../../ThePEG/Pointer/ReferenceCounted.h \
  ../../ThePEG/Pointer/ReferenceCounted.icc \
  ../../ThePEG/Pointer/RCPtr.icc \
  ../../ThePEG/Utilities/Rebinder.fh \
  ../../ThePEG/Utilities/Interval.fh \
  ../../ThePEG/Utilities/ClassDescription.fh \
  ../../ThePEG/Interface/InterfaceBase.fh \
  ../../ThePEG/Persistency/PersistentOStream.fh \
  ../../ThePEG/Persistency/PersistentIStream.fh \
  ../../ThePEG/Config/Units.h \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.fh \
  ../../ThePEG/CLHEPWrap/LorentzVector.fh \
  ../../ThePEG/CLHEPWrap/CLHEP.h \
  ../../ThePEG/CLHEPWrap/ThreeVector.fh \
  ../../ThePEG/CLHEPWrap/Transverse.fh \
  ../../ThePEG/CLHEPWrap/SystemOfUnits.h \
  ../../ThePEG/Utilities/UnitIO.h \
  ../../ThePEG/Config/Constants.h \
  ../../ThePEG/Config/std.h \
  ../../ThePEG/Config/Pointers.h \
  ../../ThePEG/Config/Containers.h \
  ../../ThePEG/Utilities/FixedSizeAllocator.h \
  ../../ThePEG/Utilities/Debug.h \
  ../../ThePEG/Utilities/Debug.icc \
  ../../ThePEG/Utilities/FixedSizeAllocator.icc \
  ../../ThePEG/Config/Complex.h \
  ../../ThePEG/Utilities/ClassDescription.h \
  ../../ThePEG/Utilities/Named.h \
  ../../ThePEG/Utilities/Named.icc \
  ../../ThePEG/Utilities/ClassTraits.h \
  ../../ThePEG/Utilities/DescriptionList.h \
  ../../ThePEG/Utilities/DescriptionList.icc \
  ../../ThePEG/Utilities/ClassDescription.icc \
  ../../ThePEG/Utilities/ClassDescription.tcc \
  ../../ThePEG/Utilities/Exception.h \
  ../../ThePEG/Utilities/Exception.fh \
  ../../ThePEG/Utilities/sstream.h \
  ../../ThePEG/Utilities/Exception.icc \
  PersistentOStream.fh \
  PersistentOStream.xh \
  PersistentOStream.icc
  PersistentIStream.o: \
  PersistentIStream.cc \
  PersistentIStream.h \
  ../../ThePEG/Config/ThePEG.h \
  ../../ThePEG/Config/config.h \
  ../../ThePEG/Pointer/Ptr.h \
  ../../ThePEG/Pointer/RCPtr.fh \
  ../../ThePEG/Pointer/PtrTraits.h \
  ../../ThePEG/Pointer/RCPtr.h \
  ../../ThePEG/Pointer/ReferenceCounted.h \
  ../../ThePEG/Pointer/ReferenceCounted.icc \
  ../../ThePEG/Pointer/RCPtr.icc \
  ../../ThePEG/Utilities/Rebinder.fh \
  ../../ThePEG/Utilities/Interval.fh \
  ../../ThePEG/Utilities/ClassDescription.fh \
  ../../ThePEG/Interface/InterfaceBase.fh \
  ../../ThePEG/Persistency/PersistentOStream.fh \
  ../../ThePEG/Persistency/PersistentIStream.fh \
  ../../ThePEG/Config/Units.h \
  ../../ThePEG/CLHEPWrap/Lorentz5Vector.fh \
  ../../ThePEG/CLHEPWrap/LorentzVector.fh \
  ../../ThePEG/CLHEPWrap/CLHEP.h \
  ../../ThePEG/CLHEPWrap/ThreeVector.fh \
  ../../ThePEG/CLHEPWrap/Transverse.fh \
  ../../ThePEG/CLHEPWrap/SystemOfUnits.h \
  ../../ThePEG/Utilities/UnitIO.h \
  ../../ThePEG/Config/Constants.h \
  ../../ThePEG/Config/std.h \
  ../../ThePEG/Config/Pointers.h \
  ../../ThePEG/Config/Containers.h \
  ../../ThePEG/Utilities/FixedSizeAllocator.h \
  ../../ThePEG/Utilities/Debug.h \
  ../../ThePEG/Utilities/Debug.icc \
  ../../ThePEG/Utilities/FixedSizeAllocator.icc \
  ../../ThePEG/Config/Complex.h \
  InputDescription.h \
  ../../ThePEG/Utilities/ClassDescription.h \
  ../../ThePEG/Utilities/Named.h \
  ../../ThePEG/Utilities/Named.icc \
  ../../ThePEG/Utilities/ClassTraits.h \
  ../../ThePEG/Utilities/DescriptionList.h \
  ../../ThePEG/Utilities/DescriptionList.icc \
  ../../ThePEG/Utilities/ClassDescription.icc \
  ../../ThePEG/Utilities/ClassDescription.tcc \
  InputDescription.icc \
  PersistentIStream.fh \
  ../../ThePEG/Utilities/Exception.h \
  ../../ThePEG/Utilities/Exception.fh \
  ../../ThePEG/Utilities/sstream.h \
  ../../ThePEG/Utilities/Exception.icc \
  PersistentIStream.icc \
  PersistentIStream.tcc \
  PersistentOStream.xh \
  PersistentOStream.fh \
  PersistentIStream.xh \
  ../../ThePEG/Utilities/DynamicLoader.h \
  ../../ThePEG/Utilities/DynamicLoader.icc

# IF YOU PUT ANYTHING HERE IT WILL GO AWAY
